name: Void Package CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: voidlinux/voidlinux-musl:latest

    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Debug workspace contents
        run: ls -la $GITHUB_WORKSPACE

      - name: 3. Install dependencies
        run: |
          set -x
          xbps-install -Syu git xtools

      - name: 4. Clone void-packages
        run: git clone --depth=1 https://github.com/void-linux/void-packages.git

      - name: 5. Link custom template
        run: ln -s $GITHUB_WORKSPACE/quickshell void-packages/srcpkgs/quickshell

      - name: 6. Show quickshell template
        run: cat void-packages/srcpkgs/quickshell/template

      - name: 7. Cache xbps-src hostdir
        uses: actions/cache@v4
        id: cache-xbps
        with:
          path: void-packages/hostdir
          key: ${{ runner.os }}-xbps-bootstrap-${{ hashFiles('void-packages/common/repo-keys/*') }}

      - name: 8. Bootstrap build environment (if not cached)
        if: steps.cache-xbps.outputs.cache-hit != 'true'
        run: |
          cd void-packages
          ./xbps-src binary-bootstrap

      - name: 9. Fix ownership
        run: chown -R $(id -u):$(id -g) void-packages

      - name: 10. Build the package
        run: |
          cd void-packages
          ./xbps-src pkg quickshell

      - name: 11. Show build artifacts (for verification)
        run: |
          echo "Build complete. Found packages:"
          ls -R void-packages/hostdir/binpkgs/
